version: 2.1

parameters:
  main-project1:
    type: boolean
    default: false
  main-project2:
    type: boolean
    default: false
  deploy-project1:
    type: boolean
    default: false
  deploy-project2:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: cimg/node:16.17.1-browsers
    working_directory: ~/project

jobs:
  shared-job:
    executor: node
    steps:
      - run: echo 'shared job success!'
  staging-job:
    executor: node
    steps:
      - run: echo 'staging job success!'
  production-job:
    executor: node
    steps:
      - run: echo 'production job success!'


workflows:
  main-project1:
    when: << pipeline.parameters.main-project1 >>
    jobs:
      - shared-job:
          name: shared-job-project1
      - staging-job:
          name: staging-job-project1
          filters:
            branches:
              only:
                - main
  deploy-project1:
    when: << pipeline.parameters.deploy-project1 >>
    jobs:
      - shared-job:
          name: shared-job-project1
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^project1-v.*/

      - production-job:
          name: production-job-project1
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^project1-v.*/

  main-project2:
    when: << pipeline.parameters.main-project2 >>
    jobs:
      - shared-job:
          name: shared-job-project2
      - staging-job:
          name: staging-job-project2
          filters:
            branches:
              only:
                - main
  deploy-project2:
    when: << pipeline.parameters.deploy-project2 >>
    jobs:
      - shared-job:
          name: shared-job-project2
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^project1-v.*/

      - production-job:
          name: production-job-project2
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^project1-v.*/
